# Generated by Django 3.2.22 on 2025-01-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='image_files/')),
                ('label', models.IntegerField(choices=[(0, 'None'), (1, 'Diatom')], default=0)),
                ('dataset', models.CharField(choices=[('train', 'Train'), ('test', 'Test')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
