# Generated by Django 3.2.22 on 2025-01-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customtest', '0002_imagedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PklData',
        ),
    ]
